version: "3"

services:
  database:
    image: mongo
    container_name: atv_final_flutter_server_mongo
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./.docker/atv_final_flutter_server_mongo:/data/db
